services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: urlite-server
    restart: always
    environment:
      - DATABASE_URL=sqlite:///app/data/urls.db?mode=rwc
      - JWT_SECRET=qA2maSzyUaGpSsO95SR7IrUr2imQVebviYhlgWiGllt
      - PORT=8080
      - BASE_URL=http://localhost:8080
      - ALLOWED_ORIGIN=http://localhost:8080
    volumes:
      - ./server/data:/app/data
      - ./frontend/dist:/app/frontend:ro
    ports:
      - "8080:8080"
