services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: urlite-server
    restart: always
    # THÊM ĐOẠN NÀY ĐỂ TRUYỀN BIẾN MÔI TRƯỜNG:
    environment:
      - DATABASE_URL=sqlite:///app/data/urls.db
      - JWT_SECRET=qA2maSzyUaGpSsO95SR7IrUr2imQVebviYhlgWiGllt
      - PORT=8080
      - BASE_URL=http://localhost:8080
      - ALLOWED_ORIGIN=http://localhost:3000
    volumes:
      - ./server/data:/app/data
    ports:
      - "8080:8080"